# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        description: Defines the type of machine to run the job on
        required: false
        default: ubuntu-latest
      registry:
        type: string
        description: The Docker registry to push the image to
        required: false
        default: ghcr.io
      image_name:
        type: string
        description: The name of the Docker image
        required: false
        default: ${{ github.repository }}
      directories:
        type: string
        description: List of directories to build (for monorepos) (as quoted list, e.g. '["foo", "bar"]')
        required: false
        default: '[""]'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

name: Build & Push Container Image

jobs:
  image:
    name: Image
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        directory: ${{ fromJSON(inputs.directories) }}
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Build Docker Image
        uses: gitops-ci-cd/.github/actions/build@main
        with:
          registry: ${{ inputs.registry }}
          image_name: ${{ inputs.image_name }}/${{ matrix.directory }}
